SELECT 'CREATE DATABASE hospital WITH OWNER = postgres ENCODING = "UTF8" LC_COLLATE = "Russian_Russia.1252" LC_CTYPE = "Russian_Russia.1252" TABLESPACE = pg_default CONNECTION LIMIT = -1;'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'hospital');

CREATE TABLE IF NOT EXISTS Doctor
(
    DoctorId SERIAL,
    FirstName CHARACTER VARYING(255) NOT NULL,
    LastName CHARACTER VARYING(255) NOT NULL,
    Position CHARACTER VARYING(255) NOT NULL,
    TimeStart CHARACTER VARYING(255) NOT NULL,
    TimeEnd CHARACTER VARYING(255) NOT NULL,
    PRIMARY KEY (DoctorId)
);

CREATE TABLE IF NOT EXISTS Patient
(
    PatientId SERIAL,
    FirstName CHARACTER VARYING(255) NOT NULL,
    LastName CHARACTER VARYING(255) NOT NULL,
    Diagnosis CHARACTER VARYING(255),
    Age INTEGER,
    PRIMARY KEY (PatientId)
);
CREATE TABLE IF NOT EXISTS PatientAcceptance
(
    DoctorId BIGINT REFERENCES doctor NOT NULL,
    PatientId BIGINT REFERENCES patient NOT NULL
);